### PR TITLE
Add QR code display modal. Addresses #80

### PR DESCRIPTION
**Pull request by duetosymmetry**
Adds a button in the vertical toolbar to toggle a modal which shares the QR code for the current room.

Changes to enable this:
- Add a `dom.classToggle` function
- Add svg icon for a QR code, [from fontawesome](https://fontawesome.com/icons/qrcode?style=solid)
- Add dependence on the [node package qrious](https://github.com/neocotic/node-qrious), which renders to canvas
- Add a `modal.info` style with a lightgray background for showing the QR code
- Add the modal element to client/main.pug, and driving code to client/main.coffee

### CODE REVIEW

**Comment by edemaine** [comment]
Thanks for all the PRs, @duetosymmetry!  I'm looking forward to reviewing these.

**Comment by duetosymmetry** [comment]
Fixed the URL that was being emitted if user navigated to path `/` instead of directly to a room. Also added documentation.

**Comment by edemaine** [comment]
Finally getting to this, I revised this to use SVG QR codes (felt more Cocreate-like, and easier to make responsive), styled better, close button, etc.  I also merged the "copy to clipboard" button with the QR button; I didn't like the QR icon, and it didn't seem like we needed multiple buttons for this purpose. Hope you like it, and sorry for the long delay!

**Comment by duetosymmetry** [comment]
LGTM, thanks for the improvements!

**Pull request merged**
